version: "3.8"

services:
  app:
    image: "ride-processing-service"
    container_name: "ride-processing-service"
    build: .
    env_file:
      - .env
    ports:
      - "7000:8080"
    networks:
      - default

networks:
  default:
