version: '3.9'

# services define individual containers and their configurations
services:

  # api gateway / reverse proxy

  # admin api (contains all generic crud endpoints)
  ride-sharing-api:
    image: ride-sharing-api
    build:
      context: .
      dockerfile: RideSharing.API/Dockerfile
    ports:
      - "5002:80"
      - "6002:443"
    networks:
      - authnet
    restart: always
    depends_on:
      - ride-sharing-api-db

  ride-sharing-api-db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: ride-sharing-api-db
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433"
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=123456Aa
    networks:
      - authnet
    restart: always

  # customer api (riders & customers only)

  # auth service api (identity provider for microservices)

# volumes are a physical areas of disk space shared between the host and the containers
# volumes:

# networks define the communication rules between containers, and between a container and the host
networks:
  authnet: # a custom network to allow the containers to interact together
