version: '3'

# services define individual containers and their configurations
services:

  # reverse proxy server
  nginx:
    restart: unless-stopped
    image: nginx:1.24.0
    container_name: nginx_server
    ports:
      - "5000:5000" # ride sharng auth api http port
      - "6000:6000" # ride sharing customer api http port
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - ridesharing-shared-net
  
  # RideSharing Auth API
  ridesharing-auth-api:
    build:
      context: ../
      dockerfile: src/RideSharing.AuthenticationAPI/Dockerfile
    container_name: ridesharing-auth-api
    restart: unless-stopped
    networks:
      - ridesharing-shared-net

  # RideSharing Customer API
  ridesharing-customer-api:
    build:
      context: ../
      dockerfile: src/RideSharing.CustomerAPI/Dockerfile
    container_name: ridesharing-customer-api
    restart: unless-stopped
    networks:
      - ridesharing-shared-net
 
  # Mailhog (local mail server)
  mailhog:
    restart: unless-stopped
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
    networks:
      - ridesharing-shared-net

# volumes are a physical areas of disk space shared between the host and the containers
# volumes:

# networks define the communication rules between containers, and between a container and the host
networks:
  ridesharing-shared-net:
    external: true
