services:
  # postgres database service
  postgres-server:
    image: 'postgis/postgis'
    container_name: postgres-server
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/data/postgres
    volumes:
      - ./data/postgres:/data/postgres
    networks:
      - ridesharing-shared-net
  # postgres database admin console
  pgadmin-server:
    image: dpage/pgadmin4
    container_name: pgadmin-server
    ports:
      - 8082:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    depends_on:
      - postgres-server
    volumes:
      - ./data/pgadmin/:/var/lib/pgadmin/
    networks:
      - ridesharing-shared-net

networks:
  ridesharing-shared-net:
    external: true
