# services define individual containers and their configurations
services:

  # MoveBangladesh Auth API
  ridesharing-auth-api:
    build:
      context: ../
      dockerfile: src/MoveBangladesh.AuthenticationAPI/Dockerfile
    container_name: ridesharing-auth-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - ridesharing-shared-net

  # MoveBangladesh Customer API
  ridesharing-customer-api:
    build:
      context: ../
      dockerfile: src/MoveBangladesh.CustomerAPI/Dockerfile
    container_name: ridesharing-customer-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - ridesharing-shared-net

  # Mailhog (local mail server)
#   mailhog:
#     restart: unless-stopped
#     image: mailhog/mailhog
#     container_name: mailhog
#     ports:
#       - "1025:1025" # SMTP port
#       - "8025:8025" # Web UI port
#     networks:
#       - ridesharing-shared-net

# volumes are a physical areas of disk space shared between the host and the containers
# volumes:

# networks define the communication rules between containers, and between a container and the host
networks:
  ridesharing-shared-net:
    external: true
