services:
  ## reverse proxy server that proxies all requests from: -
  # /auth-api/ -> ridesharing-auth-api
  # /customer-api/ -> ridesharing-customer-api
  nginx:
    restart: unless-stopped
    image: nginx:1.24.0
    container_name: nginx_server
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    networks:
      - ridesharing-shared-net

networks:
  ridesharing-shared-net:
    external: true
